### ISSUE TITLE
Throws error when decoder warns (not errors)

### ISSUE THREAD

**Issue by stephematician** [Dobatymo/turbojpeg-python#1]
Some webcameras (logitech) have extraneous bytes that cause an error to be thrown by this module's `decompress` - however they are still successfully decompressed by the library. See https://github.com/libjpeg-turbo/libjpeg-turbo/issues/157.

Whether the error is a warning or a true error can be determined by the API via (see https://github.com/libjpeg-turbo/libjpeg-turbo/issues/157#issuecomment-321011697):

> Simply ignoring the -1 return code if `tjGetErrorCode()==TJERR_WARNING` has the effect of making warnings irrelevant, which is what you want.

Also see: https://github.com/lilohuang/PyTurboJPEG/issues/7

**Comment by Dobatymo** [comment]
Fixed in v0.0.2. Please verify!

**Comment by stephematician** [comment]
Looks good to me.
