### ISSUE TITLE
Suggestion: Use system libjpeg-turbo

### ISSUE THREAD

**Issue by stephematician** [Dobatymo/turbojpeg-python#2]
Is there a reason for building libjpeg-turbo locally to the project as opposed to linking to the system library?

**Comment by Dobatymo** [comment]
Yes it's much easier for deployment and the only reasonable method for multiplatform support. Sorry I won't change this.

**Comment by stephematician** [comment]
Hmm - you could check for system libraries (e.g. via pkg-config on *nix for the location of library and headers) and then fallback to the locally-built option.

I'll have to try this myself.

**Comment by stephematician** [comment]
Also because you include lib-jpegturbo in full you should check that you are compliant with the license there: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/LICENSE.md

**Comment by Dobatymo** [comment]
> Also because you include lib-jpegturbo in full you should check that you are compliant with the license there: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/LICENSE.md

Yes that is true. The wrapper should probably be distributed under the same license as the library. I am not so familiar with the details here.
